DifficultWords Extraction Module
code-kern-ai/bricks pull request #274
Opened 2023-04-11 21:02 UTC by rpavani1998

PR checklist:
- [x] Tested by creator locally
- [ ] Tested by creator on remote App
- [ ] Tested by reviewer locally
- [ ] Tested by reviewer on remote App
- [ ] Conforms with the agreed upon code pattern

2023-04-12 13:47 UTC, LeonardPuettmannKern requested changes
Looks great, thanks for creating the PR! I think the code snippet needs a few changes, I have already provided the code for that. :) Let me know if you have any questions.

2023-04-12 13:49 UTC, LeonardPuettmannKern commented on extractors/python_functions/difficult_words_extraction/__init__.py
> +    return {"difficult_words": difficult_words}
We should also return the positon here, just as I explained it for the code_snippet.md

2023-04-14 07:25 UTC, rpavani1998 commented on extractors/python_functions/difficult_words_extraction/code_snippet.md
> +    return difficult_words
Got it!

2023-04-18 21:54 UTC, closed without merging

2023-04-20 11:47 UTC, rpavani1998 commented
Reopening the pr