filetype extractor
code-kern-ai/bricks pull request #275
Opened 2023-04-12 10:11 UTC by Ahmed-Badr01

#272 

PR checklist:
- [ ] Tested by creator locally
- [ ] Tested by creator on remote App
- [ ] Tested by reviewer locally
- [ ] Tested by reviewer on remote App
- [ ] Conforms with the agreed upon code pattern

2023-04-12 13:54 UTC, LeonardPuettmannKern requested changes
Looks great, thanks for contributing! I've added a suggestion for the code_snippet.md. Apart from that it looks good. 👍

2023-04-12 17:44 UTC, Ahmed-Badr01 commented on extractors/python_functions/filetype_extraction/code_snippet.md
> +        return filetypes
Actually, I do. I'm not sure if you are on Twitter or maybe even Skype, but I'm thinking about making another extractor, and I need to ask some questions about your comment and changes before I do that.

Let me know if either platform is an option. I currently have no presence on Discord or LinkedIn. Thank you in advance.

2023-04-18 15:23 UTC, LeonardPuettmannKern commented on extractors/python_functions/filetype_extraction/code_snippet.md
> +        return filetypes
Hi @Ahmed-Badr01 , I sadly don't have Twitter or Skype, but maybe we can just have a call over Google Meets? We've recently released a new version of bricks which changes some of the structure. If you like, I can explain everything to you then. 👍

2023-04-27 18:58 UTC, Ahmed-Badr01 commented on extractors/python_functions/filetype_extraction/code_snippet.md
> +        return filetypes
Hello, Leonard.

Google Meets sounds fine, let's have a call sometime.

2023-09-25 12:21 UTC, closed without merging