Adding n-gram generator module to generators, implements #279.
code-kern-ai/bricks pull request #393
Opened 2024-01-26 00:06 UTC by springlaughing

refinery
- [ ] Tested by creator on refinery
- [ ] Tested by reviewer on refinery
- [ ] Ensured that output of brick conforms with refinery structure (to be checked by reviewer)

API
- [x] Tested by creator on localhost:8000/docs
- [ ] Tested by reviewer on localhost:8000/docs

common code
- [x] Common code tested in notebook/ script by creator
- [ ] Common code tested in notebook/ script by reviewer
- [x] Common code contains docstrings and type hints

additional points:
- [x] Docstring and README is existing
- [x] Import statements (in `__init__.py`)
- [ ] (If necessary) Added dependency to requirements.txt
- [ ] (If necessary) Added dependency to issue for refinery env [here](https://github.com/code-kern-ai/refinery/issues/166)
- [ ] Published brick to Strapi CMS (locally)

Testing procedure: 
When testing in refinery, please ensure that the output of the brick conforms with the structure of refinery. 
For `extraction` bricks, this would be a tuple like `("label", span_start, span_end)`.
For `classification` bricks, this would be a string representing a label.
For `generator` bricks, this would either be a float, interger, string, boolean or a list, depending on the situation.

When testing the bricks, try to avoid using only one source of data. Meaning that you should not only use the `clickbait` sample
project, but also different texts with longer or more complex strings. 

A small refinery example project with a variation of texts called `bricks-test-data-project.zip` can be found in the bricks repository.

2024-01-26 13:18 UTC, LeonardPuettmannKern requested changes
The code looks great, well done and thank you for the contribution. I have tested the all snippets and only would suggest one change for the `config.py`. :-)

2024-01-26 13:18 UTC, LeonardPuettmannKern commented on generators/ngram/nltk_ngram_generator/config.py
> +        },
This section is missing the `NGRAM_SIZE` as an input, I would suggest to use this:

```suggestion
integrator_inputs={
    "name": "nltk_ngram_generator",
    "refineryDataType": RefineryDataType.TEXT.value,
    "variables": {
        "ATTRIBUTE": {
            "selectionType": SelectionType.CHOICE.value,
            "description": "only text fields",
            "optional": "false",
            "addInfo": [
                BricksVariableType.ATTRIBUTE.value,
                BricksVariableType.GENERIC_STRING.value
            ]
        },
        "NGRAM_SIZE": {
            "selectionType": SelectionType.INTEGER.value,
            "defaultValue": 2,
            "optional": "false",
            "addInfo": [
                BricksVariableType.GENERIC_INT.value
            ]
        }
    }
}
```

2024-01-26 15:57 UTC, springlaughing commented
Got it, thanks, glad to participate :)

2024-01-29 15:38 UTC, springlaughing commented
Should I do anything else for the merging?

2024-01-29 15:58 UTC, LeonardPuettmannKern reviewed
Just some renaming then it should be good to go. :)

2024-01-29 15:58 UTC, LeonardPuettmannKern commented on generators/ngram/nltk_ngram_generator/config.py
> +from . import nltk_ngram, INPUT_EXAMPLE
This should be `from . import nltk_ngram_generator, INPUT_EXAMPLE`

2024-01-29 15:58 UTC, LeonardPuettmannKern commented on generators/ngram/nltk_ngram_generator/config.py
> +        function=nltk_ngram,
Rename `nltk_ngram` to `nltk_ngram_generator`

2024-01-29 15:59 UTC, LeonardPuettmannKern commented
@springlaughing I noticed that a name in the `config.py` also need to be fixed. After that, I can approve and will merge it! Thank you.

2024-01-29 19:35 UTC, springlaughing commented
Ah, got it. Done.

2024-01-30 08:43 UTC, LeonardPuettmannKern approved these changes
Looks good, thanks again @springlaughing!

2024-01-30 08:44 UTC, merged

2024-01-30 08:44 UTC, LeonardPuettmannKern commented
Merge implementing #279.